server:
  port: 8081

spring:
  application:
    name: customer
  datasource:
    url: jdbc:mysql://mysql:3306/customer
    username: root
    password: 1234
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    addresses: rabbitmq:5672
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
