server:
  port: 8081

spring:
  application:
    name: customer
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: user
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
