version: '3.7'
services:
  db:
    container_name: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql:/data/mysql
      - ./ddl/data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped

  adminer:
    image: adminer
    networks:
      - mysql
    restart: always
    ports:
      - "8088:8080"

networks:
  mysql:
    driver: bridge

volumes:
  mysql:
