version: '3.7'
services:
  db:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0.28
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql:/data/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped
  adminer:
    image: adminer
    networks:
      - mysql
    restart: always
    ports:
      - "8088:8080"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  mysql:

volumes:
  mysql:
